#!/usr/bin/env zsh
# Users Tarball

set -u

STARTTIME=$(date +%s)
FileDate="${1:-$(date +%F)}"

CloudDir="DropBox"
remoteDir="${CloudDir}:/usertarbal"
remoteDest="${remoteDir}/${FileDate}"

localDir="usertarbal"
cd / || exit 1

[[ -d "/${localDir}" ]] || mkdir -p "/${localDir}"
[[ -d "/${localDir}/${FileDate}" ]] || mkdir -p "/${localDir}/${FileDate}"

show_time() {
    local seconds=$1 prefix=$2
    local h=$((seconds/3600))
    local m=$(((seconds%3600)/60))
    local s=$((seconds%60))
    printf '%s %02dh:%02dm:%02ds\n' "$prefix" "$h" "$m" "$s"
}

check_error() {
    local result=$1
    if [[ $result -eq 0 || $result -eq 1 ]]; then
        printf "Done! (%d)\n" "$result"
    else
        printf "FAILED! (%d)\n" "$result"
        r_errors=$((r_errors+1))
    fi
}

backupNow() {
    local User=$1
    local Dir=$2
    local FileName="${User}-dir-${FileDate}.tgz"

    printf "\n**** %s ****" "$User"
    printf "\n  **** Making "%s" tarball (/"%s/%s/%s")..." \
        "$User" "$localDir" "$FileDate" "$FileName"

    rm -f "/${localDir}/${FileDate}/${FileName}" 2>/dev/null

    tar -cvzf "/${localDir}/${FileDate}/${FileName}" \
        -X "/root/scripts/${User}-Exclude" "$Dir" \
        >"/${localDir}/${FileDate}/${FileName}.log" \
        2>"/${localDir}/${FileDate}/${FileName}.err"
    local results=$?
    check_error "$results"

    [[ -s "/${localDir}/${FileDate}/${FileName}.log" ]] || \
        rm -f "/${localDir}/${FileDate}/${FileName}.log"
    [[ -s "/${localDir}/${FileDate}/${FileName}.err" ]] || \
        rm -f "/${localDir}/${FileDate}/${FileName}.err"
}

# Work starts here
rm -f "${HOME}"/usertarbal*.err 2>/dev/null

r_errors=0

users_dirs=(
    root      /root
    bram      /home/bram
    h4hm      /home/h4hm
    y4x       /home/y4x
    tim       /home/tim
    joe       /home/joe
    linuxbrew /home/linuxbrew
)

for ((i=1; i<${#users_dirs[@]}; i+=2)); do
    U=${users_dirs[i-1]}
    D=${users_dirs[i]}
    STARTTIME2=$(date +%s)
    backupNow "$U" "$D"
    FileName="${U}-dir-${FileDate}.tgz"
    Results=$(ls -1rtAhl "/${localDir}/${FileDate}/${FileName}" | \
              awk '{print $5,$6,$7,$8,$9}')
    printf "    %s\n" "$Results"
    STOPTIME2=$(( $(date +%s) - STARTTIME2 ))
    show_time "$STOPTIME2" "    ** "$U" tarball backup completed in"
done

printf "\n**** Tarballs completed with %d errors.\n" "$r_errors"

# Move files to Dropbox
printf "**** Moving local tarball files to %s/%s/..." "$remoteDir" "$FileDate"
rclone move "/${localDir}/${FileDate}" "${remoteDest}" --cache-db-purge \
    2>"/root/${localDir}${FileDate}.err"
results=$?
if [[ $results -eq 0 || $results -eq 1 ]]; then
    echo "Done."
else
    echo "Errors."
fi

# Delete old backups
echo "**** Delete old usertarbal backups"
maxNrOfBackups=6
nrOfBackups=$(rclone lsf "${remoteDir}" --max-depth 1 | wc -l | tr -d ' ')

if [[ $nrOfBackups -gt $maxNrOfBackups ]]; then
    echo "  ** Removing old backups"
    rclone lsf "${remoteDir}" --max-depth 1 | sort -r | \
        tail -"$(( nrOfBackups - maxNrOfBackups ))" | \
    while read -r dirToRemove; do
        [[ -z $dirToRemove ]] && continue
        printf "  ** rclone purge %s/%s..." "$remoteDir" "$dirToRemove"
        rclone purge "${remoteDir}/${dirToRemove}" --drive-use-trash=false
        results=$?
        if [[ $results -eq 0 ]]; then
            echo "Done."
        else
            echo "Errors."
        fi
    done
else
    echo "  ** No old backups to delete"
fi

rm -rf "/${localDir}/${FileDate}" 2>/dev/null

[[ -s "/root/${localDir}${FileDate}.err" ]] || \
    rm -f "/root/${localDir}${FileDate}.err"

STOPTIME=$(( $(date +%s) - STARTTIME ))
echo
show_time "$STOPTIME" "**** User tarball backups completed in"
echo

ErrFileName="${HOME}/${localDir}${FileDate}.err"
if [[ -f $ErrFileName && ! -s $ErrFileName ]]; then
    rm -f "$ErrFileName"
    echo "Deleted empty file: ${ErrFileName}"
else
    echo "File does not exist or is not empty: ${ErrFileName}"
fi
